stages:
  - build
  - archive

build_project:
  tags:
    - xcode10
  stage: build
  script:
    - bundle install
    - security unlock-keychain -p quadion ~/Library/Keychains/Quadion.keychain
    - bundle exec fastlane build
