stages:
  - build
  - archive

build_project:
  tags:
    - xcode10
  stage: build
  script:
    - bundle install
    - bundle exec danger
    - bundle exec fastlane build
    - bundle exec fastlane tests
  artifacts:
    reports:
      junit: fastlane/test_output/report.junit
