stages:
  - build
  - archive

variables:
  DANGER_GITLAB_HOST: gitlab.quadiontech.com
  DANGER_GITLAB_API_BASE_URL: https://gitlab.quadiontech.com/api/v4

build_project:
  tags:
    - xcode10
  stage: build
  script:
    - bundle install
    - bundle exec danger
    - bundle exec fastlane build
    - bundle exec fastlane tests
  artifacts:
    reports:
      junit: fastlane/test_output/report.junit
